"""Validate and enrich extracted rules, then load into ExperienceKB."""

import json
import sys
import os
import uuid

sys.path.insert(0, "/data/gt/experience_kb")
from modules.knowledge_base import ExperienceKB


def enrich_rule(rule):
    """Add required fields missing from sub-agent output."""
    if "rule_id" not in rule:
        rule["rule_id"] = f"rule_{uuid.uuid4().hex[:8]}"

    # embedding_text: auto-generated by knowledge_base.py if missing, but let's add it
    parts = [
        rule.get("title", ""),
        rule.get("state_description", ""),
        rule.get("action", {}).get("description", ""),
        " ".join(rule.get("state_keywords", [])),
    ]
    rule["embedding_text"] = " ".join(p for p in parts if p).strip()

    # source info
    rule.setdefault("source_question", "sample_batch_1")
    rule.setdefault("source_trajectories", [])
    rule.setdefault("confidence", 0.8)

    return rule


def main():
    # Load rules from sub-agent output
    rules_path = "/tmp/kbqa_rules_analysis.json"
    with open(rules_path, "r", encoding="utf-8") as f:
        rules = json.load(f)

    print(f"Loaded {len(rules)} rules")

    # Enrich
    enriched = [enrich_rule(r.copy()) for r in rules]

    # Validate with knowledge_base's validator
    kb = ExperienceKB(kb_dir="/data/gt/experience_kb/data/experience_kb")
    valid = []
    for r in enriched:
        if kb._validate_rule(r):
            valid.append(r)
            print(f"  [OK] {r['rule_type']:20s} | {r['title']}")
        else:
            print(f"  [FAIL] {r.get('title', '???')}")

    print(f"\nValidated: {len(valid)}/{len(enriched)}")

    # Save to JSONL
    output_path = "/data/gt/experience_kb/data/extracted_rules/rules_batch1.jsonl"
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        for r in valid:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")
    print(f"Saved to {output_path}")

    # Try adding to KB
    try:
        added = kb.add_rules_batch(valid)
        kb.save()
        print(f"Added {len(added)} rules to KB. Total rules in KB: {len(kb.rules)}")
    except Exception as e:
        print(f"KB add failed: {e}")
        # Save enriched rules for manual inspection
        with open("/data/gt/experience_kb/data/extracted_rules/rules_batch1_enriched.json", "w") as f:
            json.dump(enriched, f, ensure_ascii=False, indent=2)


if __name__ == "__main__":
    main()
