export BASE_MODEL='your_base_model_path'
export PROJECT_NAME='your_project_name'
export HYDRA_FULL_ERROR=1
export EXPERIMENT_NAME='f0.5-stage-1-2'
export CUDA_VISIBLE_DEVICES="0,1,2,3,4,5,6,7"
export WANDB_API_KEY="your_wandb_api_key"

TRAIN_LOG='your_train_log_dir'
VAL_LOG='your_val_log_dir'

python3 -m agent_r1.src.main_agent \
    algorithm.adv_estimator=grpo \
    data.train_files=['./data/kbqa/rl_data_stage1.parquet','./data/kbqa/rl_data_stage2.parquet','./data/kbqa/rl_data_stage3.parquet'] \
    data.val_files=['your_val_file1','your_val_file2','your_val_file3'] \
    data.train_batch_size=64 \
    data.shuffle=False \
    data.max_prompt_length=4096 \
    data.max_response_length=8192 \
    data.max_response_length_single_turn=512 \
    data.use_default_tool_template=True \
    actor_rollout_ref.model.path=$BASE_MODEL \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=64 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=1 \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=1 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.stop_token_ids=[151658] \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.6 \
    actor_rollout_ref.rollout.n_repeat=8 \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=1 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    algorithm.kl_ctrl.kl_coef=0.001 \
    reward_model.reward_kwargs.beta=0.5 \
    trainer.rollout_data_dir=$TRAIN_LOG \
    trainer.validation_data_dir=$VAL_LOG \
    trainer.logger=['console','wandb'] \
    trainer.project_name=$PROJECT_NAME \
    trainer.experiment_name=$EXPERIMENT_NAME \
    trainer.n_gpus_per_node=8 \
    trainer.nnodes=1 \
    trainer.save_freq=10 \
    trainer.test_freq=10 \
    trainer.total_epochs=5 \
    trainer.val_before_train=True \
    trainer.log_val_generations=0 \
    tool.max_turns=10 \
    tool.tools=['SearchGraphPatterns','SearchTypes','ExecuteSPARQL'] \
    tool.env=kbqa \
    tool.max_tool_response_length=1500 $@